name: server

on:
 workflow_dispatch:

jobs:
  servers:
     runs-on: ubuntu-latest
     steps:
       - name: update system
         run: sudo apt-get update
  installs:
        needs: [servers]
        runs-on: ubuntu-latest
        steps:
          - name: install the nginx server
            run: sudo apt-get install nginx 
  status:
        needs:
          - servers
          - installs
        runs-on: ubuntu-latest
        steps:
           - name: check server status
             run: nginx -v
